site_name: RowBoat docs
site_url: https://docs.rowboatlabs.com
theme:
  name: material
  favicon: img/favicon.ico
nav:
  - Getting Started: setup.md
  - Overview:
    - Introduction: index.md
    - Open Source License: license.md

  - Building in Studio:
    - Create agents: create_agents.md
    - Test chats in the playground: playground.md
    - Add tools: add_tools.md
    - Update agents: update_agents.md
    - Using RAG: using_rag.md

  - API & SDK:
    - Using the API: using_the_api.md
    - Using the SDK: using_the_sdk.md

  - Concepts:
    - Agents: agents.md
    - Tools: tools.md
    - Prompts: prompts.md
